### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by robsalasco** [floere/picky#143]
```
galatea::x0r [app_name]$ bundle exec unicorn -c unicorn.rb
```

```
I, [2015-07-19T14:35:30.996819 #19314]  INFO -- : Refreshing Gem list
/Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/picky-4.31.1/lib/picky/wrappers/bundle/exact_partial.rb:21:in `load': wrong number of arguments (1 for 0) (ArgumentError)
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/picky-4.31.1/lib/picky/category_indexed.rb:13:in `load'
	from (__FORWARDING__):1:in `block in load'
	from (__FORWARDING__):1:in `each'
	from (__FORWARDING__):1:in `load'
	from (__FORWARDING__):1:in `load'
	from (__FORWARDING__):1:in `block in load'
	from (__FORWARDING__):1:in `each'
	from (__FORWARDING__):1:in `load'
	from (__INSTANCE_FORWARDING__):2:in `load'
	from config.ru:8:in `block in <main>'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `call'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
	from /Users/x0r/.rbenv/versions/2.1.2/bin/unicorn:23:in `load'
	from /Users/x0r/.rbenv/versions/2.1.2/bin/unicorn:23:in `<main>'
I, [2015-07-19T14:36:06.464222 #19354]  INFO -- : Refreshing Gem list
/Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/picky-4.31.1/lib/picky/wrappers/bundle/exact_partial.rb:21:in `load': wrong number of arguments (1 for 0) (ArgumentError)
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/picky-4.31.1/lib/picky/category_indexed.rb:13:in `load'
	from (__FORWARDING__):1:in `block in load'
	from (__FORWARDING__):1:in `each'
	from (__FORWARDING__):1:in `load'
	from (__FORWARDING__):1:in `load'
	from (__FORWARDING__):1:in `block in load'
	from (__FORWARDING__):1:in `each'
	from (__FORWARDING__):1:in `load'
	from (__INSTANCE_FORWARDING__):2:in `load'
	from config.ru:8:in `block in <main>'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `call'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
	from /Users/x0r/.rbenv/versions/2.1.2/bin/unicorn:23:in `load'
	from /Users/x0r/.rbenv/versions/2.1.2/bin/unicorn:23:in `<main>'
I, [2015-07-19T14:36:30.155830 #19385]  INFO -- : Refreshing Gem list
/Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/picky-4.31.1/lib/picky/wrappers/bundle/exact_partial.rb:21:in `load': wrong number of arguments (1 for 0) (ArgumentError)
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/picky-4.31.1/lib/picky/category_indexed.rb:13:in `load'
	from (__FORWARDING__):1:in `block in load'
	from (__FORWARDING__):1:in `each'
	from (__FORWARDING__):1:in `load'
	from (__FORWARDING__):1:in `load'
	from (__FORWARDING__):1:in `block in load'
	from (__FORWARDING__):1:in `each'
	from (__FORWARDING__):1:in `load'
	from (__INSTANCE_FORWARDING__):2:in `load'
	from config.ru:8:in `block in <main>'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `eval'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn.rb:48:in `block in builder'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `call'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:768:in `build_app!'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:137:in `start'
	from /Users/x0r/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
	from /Users/x0r/.rbenv/versions/2.1.2/bin/unicorn:23:in `load'
	from /Users/x0r/.rbenv/versions/2.1.2/bin/unicorn:23:in `<main>'
```

any idea?

**Comment by floere** [comment]
@robsalasco Hi Roberto, sorry about that! Would you mind trying again with 4.31.2? Thanks :)

**Comment by robsalasco** [comment]
wow! now it's working! thank you so much!

**Comment by floere** [comment]
@robsalasco Great 🎉 glad to hear it :)
